---
#MIT License
#
#Copyright (c) 2023 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "del_params_dsns"
output: html_document
date: '2022-12-07'
---

```{r}

library(data.table)
library(ggpubr)
library(ggplot2)

```


```{r}

continuous_variables <- c(
  'gc_content',
  'inculture',
  'inplanta'
)

legend_labels_continuous <- c(
  'AT Content',
  'Normalized in Culture RNAseq Signal',
  'Normalized in Planta RNAseq Signal'
)

axis_xlim_uppers <-c(
  1,
  1000,
  1000
)

```


```{r}

for (i in seq(from=1,to=length(continuous_variables))){
  
  variable = continuous_variables[i]
    
  legend_label = legend_labels_continuous[i]
  
  axis_xlim_upper = axis_xlim_uppers[i]
  
  print(i)
  print(variable)
  print(legend_label)
  
  ## read in values for randomly selected regions
  vector_shuffled_rice <- data.frame(fread(paste('../../pav_newest_gladieux_only_fungap/sv_callers/shuffled.',
                                            variable,'.txt', sep='')))$V1
  
  ## read in values for deletions
  vector_del_rice <- data.frame(fread(paste('../../pav_newest_gladieux_only_fungap/sv_callers/del.',
                                          variable,'.txt', sep='')))$V1
  
  # same for wheat blast
  vector_shuffled_wheat <- data.frame(fread(paste('../../pav_newest_wheat_blast_all/sv_callers/shuffled.',
                                            variable,'.txt', sep='')))$V1
  
  vector_del_wheat <- data.frame(fread(paste('../../pav_newest_wheat_blast_all/sv_callers/del.',
                                          variable,'.txt', sep='')))$V1
  
  plot_df <- data.frame(
    value = c(vector_shuffled_rice, vector_del_rice,
              vector_shuffled_wheat, vector_del_wheat),
    group = c(rep('Rice Blast Baseline',length(vector_shuffled_rice)),
              rep('Rice Blast Deletion',length(vector_del_rice)),
              rep('Wheat Blast Baseline',length(vector_shuffled_wheat)),
              rep('Wheat Blast Deletion',length(vector_del_wheat)))
  )
  
  # plot density hists for each variable
  p <- ggplot(data=plot_df, aes(x=value, color=group)) +
      stat_density(geom="line",position="identity",adjust=5)+
    ylab('Density')+
    xlab(legend_label)+
    xlim(0,axis_xlim_upper)+
    theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6)) + theme(legend.title = element_blank())+
      theme(legend.position = "none")
  
  ggsave(paste(variable, "_", 'density_plot',
               '.pdf',sep = ''), plot = p, width = 6.5/2, height = 7.25/4)

}

# get single legend for all
p <- ggplot(data=plot_df, aes(x=value, group=group, color=group)) +
  stat_density(geom="line",position="identity")+ theme_minimal()+
  ylab('Density')+
  xlab(legend_label)+
  theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6)) + theme(legend.title = element_blank())

leg <- get_legend(p)
my_legend <- as_ggplot(leg)
ggsave('legend_density_plot.pdf', plot = leg, width = 6.5, height = 0.25)

```

```{r}

continuous_variables <- c(
  'methylation',
  'H3K36me3',
  'H3K27me3',
  'H3K27ac',
  'eccdna'
)

legend_labels_continuous <- c(
  '% Methylated Cytosines',
  'Normalized H3K36me3 Signal',
  'Normalized H3K27me3 Signal',
  'Normalized H3K27ac Signal',
  'Normalized EccDNA-Seq Signal'
)

axis_xlim_uppers <-c(
  4,
  1000,
  1000,
  1000,
  1000
)

```

```{r}

## continuous variables that are only present in rice blast
for (i in seq(from=1,to=length(continuous_variables))){
  
  variable = continuous_variables[i]
    
  legend_label = legend_labels_continuous[i]
  
  axis_xlim_upper = axis_xlim_uppers[i]
  
  print(i)
  print(variable)
  print(legend_label)
  
  ## read in values for shuffled regions
  vector_shuffled_rice <- data.frame(fread(paste('../../pav_newest_gladieux_only_fungap/sv_callers/shuffled.',
                                            variable,'.txt', sep='')))$V1
  
  ## read in values for deletions
  vector_del_rice <- data.frame(fread(paste('../../pav_newest_gladieux_only_fungap/sv_callers/del.',
                                          variable,'.txt', sep='')))$V1
  
  plot_df <- data.frame(
    value = c(vector_shuffled_rice, vector_del_rice),
    group = c(rep('Rice Baseline',length(vector_shuffled_rice)),
              rep('Rice Deletion',length(vector_del_rice)))
  )
  
  p <- ggplot(data=plot_df, aes(x=value, color=group)) +
      stat_density(geom="line",position="identity",adjust=5)+
    ylab('Density')+
    xlab(legend_label)+
    xlim(0,axis_xlim_upper)+
    scale_color_manual(values=c("#F8766D","#7CAE00"))+
    theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6)) + theme(legend.title = element_blank())+
      theme(legend.position = "none")
  
  ggsave(paste(variable, "_", 'density_plot',
               '.pdf',sep = ''), plot = p, width = 6.5/2, height = 7.25/4)

}

## grab single legend for all plots
p <- ggplot(data=plot_df, aes(x=value, group=group, color=group)) +
  stat_density(geom="line",position="identity")+ theme_minimal()+
  ylab('Density')+
  xlab(legend_label)+
  scale_color_manual(values=c("#F8766D","#7CAE00"))+
  theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6)) + theme(legend.title = element_blank())

leg <- get_legend(p)
my_legend <- as_ggplot(leg)
ggsave('legend_density_plot.pdf', plot = leg, width = 6.5, height = 0.25)

```

