---
title: "rf_params_dsns"
output: html_document
date: '2022-10-24'
---

```{r}

library(data.table)
library(ggpubr)
library(ggplot2)

```

```{r}

df_gene_info_wheat_blast <-data.frame(fread('../../pav_newest_wheat_blast_all/random_forest/gene_info.cross_host.wheat_blast.txt', na.strings = ''))

df_gene_info_wheat_blast$host = "wheat"
  
df_gene_info_rice_blast <- data.frame(fread('../../pav_newest_gladieux_only_fungap/random_forest/gene_info.cross_host.rice_blast.txt', na.strings = ''))

df_gene_info_rice_blast$host = "rice"

df <- rbind(df_gene_info_rice_blast, df_gene_info_wheat_blast)

rm(df_gene_info_wheat_blast)

rm(df_gene_info_rice_blast)

```




```{r}

categorical_variables <- c(
  'tm',
  'signalp',
  'effectorp',
  'go',
  'pfam'
)

legend_labels_categorical <- c(
  'TM Domain',
  'Signal Peptide',
  'Predicted Effector',
  'GO Annotation',
  'PFAM Annotation'
)



```

```{r}

for (i in seq(from=1,to=length(categorical_variables))){
  
  variable = categorical_variables[i]
  
  legend_label = legend_labels_categorical[i]
  
  percent_pav_true_rice <- mean(
    df[[variable]][df$lineage_pav==TRUE & df$host == 'rice'], na.rm = TRUE
  )
  
  percent_pav_false_rice <- 1 - percent_pav_true_rice
    
  percent_conserved_true_rice <- mean(
     df[[variable]][df$lineage_conserved==TRUE & df$host == 'rice'], na.rm = TRUE
  )
  
  percent_conserved_false_rice <- 1 - percent_conserved_true_rice
  
  percent_pav_true_wheat <- mean(
    df[[variable]][df$lineage_pav==TRUE & df$host == 'wheat'], na.rm = TRUE
  )
  
  percent_pav_false_wheat <- 1 - percent_pav_true_wheat
    
  percent_conserved_true_wheat <- mean(
     df[[variable]][df$lineage_conserved==TRUE & df$host == 'wheat'], na.rm = TRUE
  )
  
  percent_conserved_false_wheat <- 1 - percent_conserved_true_wheat
  
  ## necessary for stacked barplot/percentage barplot plotting
  percentage <- c(percent_pav_true_rice,
                percent_pav_false_rice,
                percent_conserved_true_rice,
                percent_conserved_false_rice,
                percent_pav_true_wheat,
                percent_pav_false_wheat,
                percent_conserved_true_wheat,
                percent_conserved_false_wheat)
  
  value <- c("True", 
                "False",
                "True", 
                "False",
                "True", 
                "False",
                "True", 
                "False")
  
  og_group <- c("PAV", "PAV",
                "Conserved", "Conserved",
                "PAV", "PAV",
                "Conserved", "Conserved")
  obs_over_expected_rice <- round(percent_pav_true_rice/percent_conserved_true_rice, 1)
  obs_over_expected_wheat <- round(percent_pav_true_wheat/percent_conserved_true_wheat,1)
  
  host <- c(paste("Rice Blast \n PAV/Cons. = ", obs_over_expected_rice,sep=''),
            paste("Rice Blast \n PAV/Cons. = ", obs_over_expected_rice,sep=''),
            paste("Rice Blast \n PAV/Cons. = ", obs_over_expected_rice,sep=''),
            paste("Rice Blast \n PAV/Cons. = ", obs_over_expected_rice,sep=''),
            paste("Wheat Blast \n PAV/Cons. = ",
                  obs_over_expected_wheat,sep=''),
            paste("Wheat Blast \n PAV/Cons. = ",
                  obs_over_expected_wheat,sep=''),
            paste("Wheat Blast \n PAV/Cons. = ",
                  obs_over_expected_wheat,sep=''),
            paste("Wheat Blast \n PAV/Cons. = ",
                  obs_over_expected_wheat,sep=''))
  
  
  plot_df <- data.frame(percentage,value,og_group,host)
  
  plot_df$value <- factor(plot_df$value,levels = c("True", "False"))
  
  plot_df$og_group <- factor(plot_df$og_group,levels = c("PAV", "Conserved"))
  
  
  p <- ggplot(plot_df, aes(x = og_group, y = percentage, fill = value)) +
    geom_bar(stat = 'identity', position = 'fill') +
    theme_minimal() +
    xlab("") + ylab("Percentage") +
    scale_fill_discrete(labels=c(
      legend_label,
      paste('No ',legend_label, sep='')
    ))+
    facet_grid(. ~ host)+
    ggtitle(legend_label)+
    theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6)) + theme(legend.title = element_blank())+
  theme(strip.text.x = element_text(size = 6))+
    theme(legend.position = "none")
  
  ggsave(paste(variable, "_", 'stacked_barplot',
               '.pdf',sep = ''), plot = p, width = 6.5/3, height = 4.5/2)
}

p <- ggplot(plot_df, aes(x = og_group, y = percentage, fill = value)) +
  geom_bar(stat = 'identity', position = 'fill') +
  theme_minimal() +
  xlab("") + ylab("Percentage") +
  scale_fill_discrete(labels=c(
    legend_label,
    paste('No ',legend_label, sep='')
  ))+
  facet_grid(. ~ host)+
  ggtitle(legend_label)+
  theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6)) + theme(legend.title = element_blank())+
theme(strip.text.x = element_text(size = 6))+
  scale_fill_discrete(labels=c('True', 'False'))

leg <- get_legend(p)
my_legend <- as_ggplot(leg)
ggsave('legend_stacked_barplots.pdf', plot = leg, width = 6.5/3, height = 4.5/2)

```

```{r}

continuous_variables <- c(
  'gene_gc',
  'flanking_1kb_gc',
  'lengths',
  'cm_expression',
  'ip_expression'
)

legend_labels_continuous <- c(
  'Gene AT Content',
  'Average Flanking AT Content (1kbp)',
  'Gene Length',
  'Expression: Culture (TPM)',
  'Expression: In Planta (TPM)'
)

axis_xlim_uppers <-c(
  1,
  1,
  7500,
  100,
  100
)

```


```{r}

for (i in seq(from=1,to=length(continuous_variables))){
  
  variable = continuous_variables[i]
    
  legend_label = legend_labels_continuous[i]
  
  axis_xlim_upper = axis_xlim_uppers[i]
  
  print(i)
  print(variable)
  print(legend_label)
  
  vector_variable_pav_rice <- df[[variable]][df$lineage_pav == TRUE &
                                               df$host == "rice"]
  
  vector_variable_conserved_rice <- df[[variable]][df$lineage_conserved == TRUE &
                                               df$host == "rice"]
  
  vector_variable_pav_wheat <- df[[variable]][df$lineage_pav == TRUE &
                                               df$host == "wheat"]
  
  vector_variable_conserved_wheat <- df[[variable]][df$lineage_conserved == TRUE &
                                               df$host == "wheat"]
  
  plot_df <- data.frame(
    value = c(vector_variable_pav_rice, vector_variable_conserved_rice,
              vector_variable_pav_wheat, vector_variable_conserved_wheat),
    group = c(rep('Rice Blast (PAV)',length(vector_variable_pav_rice)),
              rep('Rice Blast (Conserved)',length(vector_variable_conserved_rice)),
              rep('Wheat Blast (PAV)',length(vector_variable_pav_wheat)),
              rep('Wheat Blast (Conserved)',length(vector_variable_conserved_wheat)))
  )
  
  p <- ggplot(data=plot_df, aes(x=value, color=group)) +
      stat_density(geom="line",position="identity",adjust=5)+
    ylab('Density')+
    xlab(legend_label)+
    xlim(0,axis_xlim_upper)+
    theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6)) + theme(legend.title = element_blank())+
      theme(legend.position = "none")
  
  ggsave(paste(variable, "_", 'density_plot',
               '.pdf',sep = ''), plot = p, width = 6.5/3, height = 3.75/2)

}

p <- ggplot(data=plot_df, aes(x=value, group=group, color=group)) +
  stat_density(geom="line",position="identity")+ theme_minimal()+
  ylab('Density')+
  xlab(legend_label)+
  theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6)) + theme(legend.title = element_blank())

leg <- get_legend(p)
my_legend <- as_ggplot(leg)
ggsave('legend_density_plot.pdf', plot = leg, width = 6.5, height = 0.25)

```
```{r}
  
df <- data.frame(fread('../../pav_newest_gladieux_only_fungap/random_forest/gene_info.full_model.rice_blast.txt', na.strings = ''))


```



```{r}

continuous_variables_no_wheat <- c(
  'methylation',
  'H3K36me3',
  'H3K27me3',
  'H3K27ac',
  'eccdna_cov'
)

legend_labels_continuous_no_wheat <- c(
  '% Methylated Cytosines',
  'Normalized H3K36me3 Signal',
  'Normalized H3K27me3 Signal',
  'Normalized H3K27ac Signal',
  'Normalized EccDNA-Seq Signal'
)

# axis_xlim_uppers_no_wheat <-c(
#   1,
#   200,
#   300,
#   300,
#   100
# )

axis_xlim_uppers_no_wheat <-c(
  2,
  400,
  600,
  600,
  200
)

```

```{r}

for (i in seq(from=1,to=length(continuous_variables_no_wheat))){
  
  variable = continuous_variables_no_wheat[i]
    
  legend_label = legend_labels_continuous_no_wheat[i]
  
  axis_xlim_upper = axis_xlim_uppers_no_wheat[i]
  
  print(i)
  print(variable)
  print(legend_label)
  
  vector_variable_pav_rice <- df[[variable]][df$lineage_pav == TRUE]
  
  vector_variable_conserved_rice <- df[[variable]][df$lineage_conserved == TRUE]
  
  
  plot_df <- data.frame(
    value = c(vector_variable_pav_rice, vector_variable_conserved_rice),
    group = c(rep('Rice PAV',length(vector_variable_pav_rice)),
              rep('Rice Conserved',length(vector_variable_conserved_rice)))
  )
  
  conserved_median <- mean(plot_df$value[plot_df$group == "Rice Conserved"])
  pav_median <- mean(plot_df$value[plot_df$group == "Rice PAV"])
  
  p <- ggplot(data=plot_df, aes(x=value, color=group)) +
      stat_density(geom="line",position="identity",adjust=5)+
    ylab('Density')+
    xlab(legend_label)+
    xlim(0,axis_xlim_upper)+
    scale_color_manual(values=c("#F8766D","#7CAE00"),labels=c(conserved_median,pav_median))+
    theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=8) , legend.title=element_text(size=6), legend.text=element_text(size=6)) + theme(legend.title = element_blank())+
      theme(legend.position = 'none')
  
  ggsave(paste(variable, "_", 'density_plot',
               '.pdf',sep = ''), plot = p, width = 6.5/3, height = 3.75/2)

}

```


