---
#MIT License
#
#Copyright (c) 2023 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

title: "plot_phylogeny"
output: html_document
date: '2022-11-28'
---

```{r}
library(phytools)
library(ape)
library(data.table)

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```


```{r}
# read in new tree

tree = read.tree(file='Single_Copy_Orthologue_Sequences_msas_combined.trimmed.fasttree')

tree = root(tree, outgroup = "NI907",resolve.root=TRUE)

# prune NI907

tree <- drop.tip(tree,tree$tip.label[match("NI907", tree$tip.label)])

str_split_vector <- function(x, string){
  output_vector <- c()
  for ( item in x ) {
    output <- strsplit(item, string)[[1]][1]
    output_vector <- c(output_vector, output)
  }
  return(output_vector)
}

tree$tip.label <- str_split_vector(tree$tip.label, '_')

write.tree(tree, file='test_rooted_tree.txt')

```



```{r}
## read lineage_info

lineage_info <- data.frame(fread('lineage_info.txt'))

colnames(lineage_info) <- c('isolate', 'lineage')

lineage_info[nrow(lineage_info)+1,] <- c("GCA012979135.1", 0)

# pick colors for lineages
lineage_info$color <- NA

lineage_info$color[lineage_info$lineage==0] = cbbPalette[5]
lineage_info$color[lineage_info$lineage==1] = "black"
lineage_info$color[lineage_info$lineage==2] = cbbPalette[7]

lineage_info <- lineage_info[match(tree$tip.label, lineage_info$isolate),]

```


```{r}
tree$tip.label
```

```{r}

replacement_dict <- c(
'GCA001675595.1' = 'BdJes16-1',
'GCA001675605.1' = 'BdMeh16-1',
'GCA001675615.1' = 'BdBar16-1',
'GCA002218425.1' = 'Py22.1',
'GCA002218435.1' = 'Py5020',
'GCA002218465.1' = 'B2',
'GCA002924665.1' = 'WHTQ',
'GCA002924685.1' = 'WBKY11',
'GCA002924745.1' = 'T25',
'GCA002925325.1' = 'Br130',
'GCA002925335.1' = 'Br7',
'GCA002925345.1' = 'Br80',
'GCA004785725.2' = 'B71',
'GCA012490805.1' = 'PR01-37.V.3.07',
'GCA012490815.1' = 'PR01-37.V.1.05',
'GCA900474545.3' = 'BR32',
'GCA905109085.1' = 'BTGP1_b',
'GCA905109095.1' = 'BTJP4_12',
'GCA905109105.1' = 'BTJP4_11',
'GCA905109115.1' = 'BTBaB1',
'GCA905109125.1' = 'BTBa_2',
'GCA905109245.1' = 'BTJP4_16',
'GCA905109485.1' = 'BTJP4_18',
'GCA905109745.1' = 'BTJP4_6',
'GCA905109755.1' = 'BTJP_4_2',
'GCA905109785.1' = 'BTJP4_3',
'GCA905109815.1' = 'BTMP_S13_1',
'GCA905109825.1' = 'BTGP_6_g',
'GCA905109845.1' = 'BTJP_4_15',
'GCA905109915.1' = 'BTJP_4_9',
'GCA905114805.1' = 'BTGP_6_e',
'GCA905114815.1' = 'BTGP_6_f',
'GCA905114825.1' = 'BTGP_6_h',
'GCA905125175.1' = 'BTJP_4_1',
'GCA905186785.1' = 'BTJP4_5',
'GCA905186795.1' = 'BTMP_S_13_2'
)


```

```{r}

tree$tip.label <- unname(replacement_dict[match(tree$tip.label, names(replacement_dict))])

```




```{r}

## plot phylogeny, margins are important to get it to fit properly
pdf('wheat_blast_labeled_tree.pdf', width=6.5, height=6.5)
par(mar = c(1, 1, 1, 1))
plot(tree, type = "fan",tip.color=lineage_info$color,cex=0.5)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=cbind(as.numeric(tree$node.label),1-as.numeric(tree$node.label)),
    piecol=c("black","white"),cex=0.2)
add.scale.bar()
dev.off()
```
