---
#MIT License
#
#Copyright (c) 2023 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "go_enrichment"
output: html_document
---

```{r}

library(topGO)
library(ggplot2)
localGetTermsDefinition<-getFromNamespace(".getTermsDefinition", "topGO")

```

```{r}

# make a df with all ontologies
df_all_onts <- data.frame(matrix(ncol = 6, nrow = 0))

colnames(df_all_onts) <- c("terms", "annotated", "significant", "expected", "pvalue", "observed_expected_ratio")

## loop through ontologies and calculate enrichments
for (ontology in c('CC', 'BP', 'MF')) {
  # use in go ids per OG
  geneID2GO <-  readMappings("Orthogroups_GO_ids.txt")

  geneNames <- names(geneID2GO)
  
  # read in lineage differentiating pav ogs
  myInterestingGenes <- as.character(read.csv("../pca_heat_map_phylogeny/lineage_differentiating_pavs.txt",header=F, stringsAsFactors=FALSE, colClasses="character")$V1)
  geneList <- factor(as.integer(geneNames %in% myInterestingGenes))
  names(geneList) <- geneNames
  
  GOdata <- new("topGOdata", ontology = ontology, allGenes = geneList, annot = annFUN.gene2GO, gene2GO = geneID2GO)
  
  # use fisher's exact test with the weighted algorithm
  test.stat <- new("weightCount", testStatistic = GOFisherTest, name = "Fisher test")

  resultFisher <- getSigGroups(GOdata, test.stat)
  
  pvalFisher <- score(resultFisher)
  
  allRes <- GenTable(GOdata, weight = resultFisher, orderBy = "weight", ranksOf = "classic", topNodes=20)
  
  terms <- localGetTermsDefinition(allRes$GO.ID, ontology(GOdata), numChar=1000)
  
  allRes_df <- data.frame(terms, allRes$Annotated, allRes$Significant, allRes$Expected, allRes$weight)
  
  colnames(allRes_df) <- c('terms', 'annotated', 'significant', 'expected', 'pvalue')
  
  # take -log10 p-value
  allRes_df$pvalue <- -log10(as.numeric(as.character(allRes_df$pvalue)))
  
  # calculate observed over expected ratio
  allRes_df$observed_expected_ratio <- allRes_df$significant/allRes_df$expected
  
  allRes_df$terms <- factor(allRes_df$terms, levels = allRes_df$terms[order(allRes_df$pvalue)])

  # output tables per ontology
  output.file <- file(paste(ontology, '_pav_ogs_enrichment.txt', sep = ''), "wb") ## to get unix line endings

  write.table(allRes, file = output.file, quote = FALSE, col.names = FALSE, row.names = FALSE)

  close(output.file)
  
  if ( ontology == 'CC') {
    title = 'Cellular Component'
  } else if (ontology == 'BP') {
    title = 'Biological Pathway'
  } else if (ontology == 'MF') {
    title = 'Molecular Function'
  }

  # pvalue 0.05 cutoff
    
  allRes_df <- allRes_df[allRes_df$pvalue > -log10(0.05),]
  
  # make sure at least 3 PAV OGs are within that GO term
  
  allRes_df <- allRes_df[allRes_df$significant >= 3,]
  
  # add to df of all ontologies
  df_all_onts <- rbind(df_all_onts, allRes_df)
  
  # plot per ontology
  p <- ggplot(allRes_df, aes(x = observed_expected_ratio, y = factor(terms))) +
    geom_point(aes(color=pvalue, size=annotated)) + theme_classic() +
    scale_colour_gradient(low = "blue", high = "red") +
    geom_rect(mapping=aes(xmin=-Inf, xmax=1, ymin=-Inf, ymax=Inf), color="grey", alpha=0.01) + # rectangle shows the mark for observed/expected is 1
    xlab("Observed count over expected count") + ylab(title) + labs(color = "-Log10 p-value", size = "Number of genes \nwith annotation")+theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_text(size=8))+
    guides(colour = guide_colorbar(order = 1), 
                size = guide_legend(order = 2))
  
  ggsave(paste(ontology, '_pav_ogs_enrichment.pdf', sep = ''), plot = p, width = 6.5, height = 3.5)
  
}

# fix some term names so they fit in the plot better

df_all_onts$terms <- as.character(df_all_onts$terms)

df_all_onts$terms[df_all_onts$terms == "oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen"] <- "oxidoreductase activity, acting on paired donors,\n with incorporation or reduction of molecular oxygen"
 
df_all_onts$terms <- as.factor(df_all_onts$terms)

## plot all ontologies

p <- ggplot(df_all_onts, aes(x = observed_expected_ratio, y = factor(terms))) +
  geom_point(aes(color=pvalue, size=annotated)) + theme_classic() +
  scale_colour_gradient(low = "blue", high = "red") +
  xlab("Observed count over expected count") + ylab('')+ labs(color = "-Log10 p-value", size = "Number of orthogroups \nwith annotation")+theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_text(size=8))+
  guides(colour = guide_colorbar(order = 1),
              size = guide_legend(order = 2))

ggsave(paste('all_onts_pav_ogs_enrichment.pdf', sep = ''), plot = p, width = 6.5, height = 3.5)

```


