---
#MIT License
#
#Copyright (c) 2023 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "dependence_heatmaps"
output: html_document
date: '2022-12-02'
---

```{r}
library(data.table)
library(ggplot2)
```


```{r}

# subset continuous and categorical columns

cont_cols <- c(
'gene_gc',
'flanking_1kb_gc',
'lengths',
'H3K27ac',
'H3K27me3',
'H3K36me3',
'cm_expression',
'ip_expression',
'eccdna_cov',
'methylation'
)

cat_cols <- c(
'any_te',
'gene_nearby',
'tm',
'signalp',
'effectorp',
'go',
'pfam'
)

```

```{r}

## import previously generated dependency matrix
df <- data.frame(fread('dependency_matrix.gene_info.full_model.rice_blast.txt', stringsAsFactors = FALSE,header=TRUE))

rownames(df) <- df$x

df <- subset(df, select = -c(x))

df <- df[rownames(df) %in% cat_cols,]

#plot f1 first so start with categorical values
df <- df[, c('f1',cat_cols, cont_cols)]
df <- df[cat_cols,]

## fix all column and rownames
colnames(df)[colnames(df) == 'f1'] <- 'Model Performance (F1)'

colnames(df)[colnames(df) == 'H3K27me3'] <- 'H3K27me3 Signal'
colnames(df)[colnames(df) == 'lengths'] <- 'Gene length'
colnames(df)[colnames(df) == 'flanking_1kb_gc'] <- 'Flanking GC Content'
colnames(df)[colnames(df) == 'pfam'] <- 'Has PFAM Annotation?'
colnames(df)[colnames(df) == 'eccdna_cov'] <- 'CircleSeq Signal'
colnames(df)[colnames(df) == 'any_te'] <- 'Has TE Nearby?'
colnames(df)[colnames(df) == 'H3K36me3'] <- 'H3K36me3 Signal'
colnames(df)[colnames(df) == 'methylation'] <- '% Methylated Cytosines'
colnames(df)[colnames(df) == 'go'] <- 'Has GO Annotation?'
colnames(df)[colnames(df) == 'H3K27ac'] <- 'H3K27ac Signal'
colnames(df)[colnames(df) == 'cm_expression'] <- 'Expression in Culture'
colnames(df)[colnames(df) == 'gene_nearby'] <- 'Has Gene Nearby?'
colnames(df)[colnames(df) == 'tm'] <- 'Has TM Domain?'
colnames(df)[colnames(df) == 'signalp'] <- 'Has Signal Peptide?'
colnames(df)[colnames(df) == 'gene_gc'] <- 'Gene GC Content'
colnames(df)[colnames(df) == 'ip_expression'] <- 'Expression in Planta'
colnames(df)[colnames(df) == 'effectorp'] <- 'Is Predicted Effector?'

rownames(df)[rownames(df) == 'H3K27me3'] <- 'H3K27me3 Signal'
rownames(df)[rownames(df) == 'lengths'] <- 'Gene length'
rownames(df)[rownames(df) == 'flanking_1kb_gc'] <- 'Flanking GC Content'
rownames(df)[rownames(df) == 'pfam'] <- 'Has PFAM Annotation?'
rownames(df)[rownames(df) == 'eccdna_cov'] <- 'CircleSeq Signal'
rownames(df)[rownames(df) == 'any_te'] <- 'Has TE Nearby?'
rownames(df)[rownames(df) == 'H3K36me3'] <- 'H3K36me3 Signal'
rownames(df)[rownames(df) == 'methylation'] <- '% Methylated Cytosines'
rownames(df)[rownames(df) == 'go'] <- 'Has GO Annotation?'
rownames(df)[rownames(df) == 'H3K27ac'] <- 'H3K27ac Signal'
rownames(df)[rownames(df) == 'cm_expression'] <- 'Expression in Culture'
rownames(df)[rownames(df) == 'gene_nearby'] <- 'Has Gene Nearby?'
rownames(df)[rownames(df) == 'tm'] <- 'Has TM Domain?'
rownames(df)[rownames(df) == 'signalp'] <- 'Has Signal Peptide?'
rownames(df)[rownames(df) == 'gene_gc'] <- 'Gene GC Content'
rownames(df)[rownames(df) == 'ip_expression'] <- 'Expression in Planta'
rownames(df)[rownames(df) == 'effectorp'] <- 'Is Predicted Effector?'

```


```{r}

# reformat dataframe for plotting
f1_mat <- melt(as.matrix(df))

f1_mat$value <- as.character(f1_mat$value)

f1_mat[f1_mat == 'x'] <- NA

f1_mat$value <- round(as.numeric(f1_mat$value),2)

```


```{r}

# plot heatmap for f1, only categorical values on rownames
p <- ggplot(data = f1_mat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white",
   midpoint = 0, limit = c(-1,1), space = "Lab",
   name="Point-Biserial\nCorrelation") + ## this is just a placeholder
  theme_minimal()+
  geom_text(aes(Var2, Var1, label = value), color = "black", size = 6*0.36)+
  xlab('Decrease in F1 When Predictive Variable is Permuted in Testing Data')+
  ylab('Model Trained to Predict')+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
         axis.text = element_text(size=6), legend.text=element_text(size=6),
        legend.title = element_text(size=6),
        legend.position = 'none',
        axis.title.x = element_text(hjust=0.6, size=8),
        axis.title.y = element_text(size=8))

ggsave('cat_dependence_heatmap.pdf', plot = p, width = 6.5, height = 6.5/2)

```

```{r}


## import previously generated dependency matrix
df <- data.frame(fread('dependency_matrix.gene_info.full_model.rice_blast.txt', stringsAsFactors = FALSE,header=TRUE))

rownames(df) <- df$x

df <- subset(df, select = -c(x))

#then plot r2 with continuous values
df <- df[rownames(df) %in% cont_cols,]

df <- df[, c('f1',cont_cols, cat_cols)]
df <- df[cont_cols,]

colnames(df)[colnames(df) == 'H3K27me3'] <- 'H3K27me3 Signal'
colnames(df)[colnames(df) == 'lengths'] <- 'Gene length'
colnames(df)[colnames(df) == 'flanking_1kb_gc'] <- 'Flanking GC Content'
colnames(df)[colnames(df) == 'pfam'] <- 'Has PFAM Annotation?'
colnames(df)[colnames(df) == 'eccdna_cov'] <- 'CircleSeq Signal'
colnames(df)[colnames(df) == 'any_te'] <- 'Has TE Nearby?'
colnames(df)[colnames(df) == 'H3K36me3'] <- 'H3K36me3 Signal'
colnames(df)[colnames(df) == 'methylation'] <- '% Methylated Cytosines'
colnames(df)[colnames(df) == 'go'] <- 'Has GO Annotation?'
colnames(df)[colnames(df) == 'H3K27ac'] <- 'H3K27ac Signal'
colnames(df)[colnames(df) == 'cm_expression'] <- 'Expression in Culture'
colnames(df)[colnames(df) == 'gene_nearby'] <- 'Has Gene Nearby?'
colnames(df)[colnames(df) == 'tm'] <- 'Has TM Domain?'
colnames(df)[colnames(df) == 'signalp'] <- 'Has Signal Peptide?'
colnames(df)[colnames(df) == 'gene_gc'] <- 'Gene GC Content'
colnames(df)[colnames(df) == 'ip_expression'] <- 'Expression in Planta'
colnames(df)[colnames(df) == 'effectorp'] <- 'Is Predicted Effector?'

rownames(df)[rownames(df) == 'H3K27me3'] <- 'H3K27me3 Signal'
rownames(df)[rownames(df) == 'lengths'] <- 'Gene length'
rownames(df)[rownames(df) == 'flanking_1kb_gc'] <- 'Flanking GC Content'
rownames(df)[rownames(df) == 'pfam'] <- 'Has PFAM Annotation?'
rownames(df)[rownames(df) == 'eccdna_cov'] <- 'CircleSeq Signal'
rownames(df)[rownames(df) == 'any_te'] <- 'Has TE Nearby?'
rownames(df)[rownames(df) == 'H3K36me3'] <- 'H3K36me3 Signal'
rownames(df)[rownames(df) == 'methylation'] <- '% Methylated Cytosines'
rownames(df)[rownames(df) == 'go'] <- 'Has GO Annotation?'
rownames(df)[rownames(df) == 'H3K27ac'] <- 'H3K27ac Signal'
rownames(df)[rownames(df) == 'cm_expression'] <- 'Expression in Culture'
rownames(df)[rownames(df) == 'gene_nearby'] <- 'Has Gene Nearby?'
rownames(df)[rownames(df) == 'tm'] <- 'Has TM Domain?'
rownames(df)[rownames(df) == 'signalp'] <- 'Has Signal Peptide?'
rownames(df)[rownames(df) == 'gene_gc'] <- 'Gene GC Content'
rownames(df)[rownames(df) == 'ip_expression'] <- 'Expression in Planta'
rownames(df)[rownames(df) == 'effectorp'] <- 'Is Predicted Effector?'

```

```{r}

# reformat dataframe for plotting
r2_mat <- melt(as.matrix(df))

r2_mat$value <- as.character(r2_mat$value)

r2_mat[r2_mat == 'x'] <- NA

r2_mat$value <- round(as.numeric(r2_mat$value),2)


```

```{r}

# plot heatmap for r2, only continuous values on rownames
p <- ggplot(data = r2_mat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white",
   midpoint = 0, limit = c(-1,1), space = "Lab",
   name="Point-Biserial\nCorrelation", oob = scales::squish) + ## squish so any value above 1 stays red
  theme_minimal()+
  geom_text(aes(Var2, Var1, label = value), color = "black", size = 6*0.36)+
  xlab(expression(paste('Decrease in ', R^2,' When Predictive Variable is Permuted in Testing Data', sep='')))+
  ylab('Model Trained to Predict')+
  scale_x_discrete(labels=c(
    expression(paste("Model Performance (", R^2,")")),
    as.character(unique(r2_mat$Var2))[2:length(unique(r2_mat$Var2))]
  )) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
         axis.text = element_text(size=6), legend.text=element_text(size=6),
        legend.title = element_text(size=6),
        legend.position = 'none',
        axis.title.x = element_text(hjust=0.6, size=8),
        axis.title.y = element_text(size=8))

ggsave('cont_dependence_heatmap.pdf', plot = p, width = 6.5, height = 6.5/2)


```

