---
#MIT License
#
#Copyright (c) 2023 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "confusion_matrix_r"
output: html_document
date: '2022-11-03'
---

```{r}
library(ggplot2)
```

```{r}

### order
# TP
# FN
# FP
# TN

# manual input
datas <- list(
  c(2321.66, 178.16,  376.34,  81445.23), # rice blast full model
  c(2345.73, 198.1,   378.58,  82844.18), # rice blast subset model
  c(1954.63, 71.79,   106.05,  42379.48), # wheat blast subset model
  c(1779.16, 17126.84,        7437.6,  387401.4), # train on rice blast, test on wheat blast
  c(2420.58, 24282.42,        7106.6,  856019.4) # train on wheat blast, test on rice blast
)

titles <- c(
  "Full Model Trained and \nTested on Subset MoO Data",
  "Reduced Model Trained and \nTested on Subset MoO Data",
  "Model Trained and \nTested on Subset MoT Data",
  "Reduced Model Trained on Subset \nMoO Data and Tested on MoT Data",
  "Model Trained on Subset MoT \nData and Tested on MoO Data"
)

outputs <- c(
  'rice_full_model_confusion_matrix.pdf',
  'rice_partial_model_confusion_matrix.pdf',
  'wheat_partial_model_confusion_matrix.pdf',
  'rice_first_cross_host_confusion_matrix.pdf',
  'wheat_first_cross_host_confusion_matrix.pdf'
)

```


```{r}

for (i in seq(from=1,to=length(outputs))){
  data <- unlist(datas[i])
  title <- titles[i]
  output <- outputs[i]
  
  
  TClass <- factor(c("PAV Gene", "PAV Gene", "Not PAV Gene", "Not PAV Gene"))
  PClass <- factor(c("PAV Gene", "Not PAV Gene", "PAV Gene", "Not PAV Gene"))
  judgement<- c("good", "bad", "bad","good")
  
  data <- round(data, digits=0)
  
  # convert to percentages
  data <- round(data/sum(data)*100, digits = 2)
  
  data <- as.character(data)
  
  data <- paste(data, '%', sep ='')
  
  df <- data.frame(TClass, PClass, data,judgement)
  
  
  # just plotting a simple confusion matrix
  p <- ggplot(data =  df, mapping = aes(x = TClass, y = PClass,fill=judgement)) +
      geom_tile()+
    geom_text(aes(label = data),size=(6*0.352777778)) +
    ylab('Predicted Label')+
    xlab('True Label')+
    scale_fill_manual(values = c(good="#0277bd", bad="red"))+
    ggtitle(title)+
    theme_classic()+
    theme(legend.position = "none")+
    theme(axis.text=element_text(size=6), axis.title=element_text(size=8), 
          legend.title=element_text(size=8),plot.title=element_text(size=8,hjust=0.75),
          plot.title.position = "plot")
  
  ggsave(output, plot = p, width = 6.5/2, height = 2)
}

```

```{r}
titles <- c(
  "Full Model Trained and \nTested on Subset MoO Data",
  "Reduced Model Trained and \nTested on Subset MoO Data",
  "Model Trained and \nTested on Subset MoT Data",
  "Reduced Model Trained on Subset \nMoO Data and Tested on MoT Data",
  "Model Trained on Subset MoT \nData and Tested on MoO Data"
)

outputs <- c(
  'rice_full_model_confusion_matrix_raw_counts.pdf',
  'rice_partial_model_confusion_matrix_raw_counts.pdf',
  'wheat_partial_model_confusion_matrix_raw_counts.pdf',
  'rice_first_cross_host_confusion_matrix_raw_counts.pdf',
  'wheat_first_cross_host_confusion_matrix_raw_counts.pdf'
)

```

```{r}

for (i in seq(from=1,to=length(outputs))){
  data <- unlist(datas[i])
  title <- titles[i]
  output <- outputs[i]
  
  
  TClass <- factor(c("PAV Gene", "PAV Gene", "Not PAV Gene", "Not PAV Gene"))
  PClass <- factor(c("PAV Gene", "Not PAV Gene", "PAV Gene", "Not PAV Gene"))
  judgement<- c("good", "bad", "bad","good")
  
  data <- round(data, digits=0)
  
  data <- as.character(data)
  
  data <- prettyNum(data, big.mark = ",", scientific = FALSE)
  
  df <- data.frame(TClass, PClass, data,judgement)
  
  
  # just plotting a simple confusion matrix
  p <- ggplot(data =  df, mapping = aes(x = TClass, y = PClass,fill=judgement)) +
      geom_tile()+
    geom_text(aes(label = data),size=(6*0.352777778)) +
    ylab('Predicted Label')+
    xlab('True Label')+
    scale_fill_manual(values = c(good="#0277bd", bad="red"))+
    ggtitle(title)+
    theme_classic()+
    theme(legend.position = "none")+
    theme(axis.text=element_text(size=6), axis.title=element_text(size=8), 
          legend.title=element_text(size=8),plot.title=element_text(size=8,hjust=0.75),
          plot.title.position = "plot")
  
  ggsave(output, plot = p, width = 6.5/2, height = 2)
}

```

```{r}
x <- c(1000,10000)
prettyNum(x, big.mark = ",", scientific = FALSE)
```

