---
#MIT License
#
#Copyright (c) 2023 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "profile_plots"
output: html_document
date: '2022-10-12'
---

```{r}
library(data.table)
library(ggplot2)
library(ggpubr)
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


```

```{r}
# read in tab output for plot profiler

hosts <- c(
  'rice',
  'wheat'
)

paths <- c(
  '../../pav_newest_gladieux_only_fungap/sv_callers/',
  '../../pav_newest_wheat_blast_all/sv_callers/'
)

regions_bed <- c(
  'all_DEL.bed',
  'gene_DEL.bed',
  'te_DEL.bed',
  'shuffled_DEL.bed',
  'all_genes.bed',
  'all_tes.bed'
)

regions <- c(
  'All Deletions',
  'Gene-containing Deletions',
  'TE-containing Deletions',
  'Random',
  'All Genes',
  'All TEs'
)

treatment_file_endings <- c(
  '_genes.tab',
  '_tes.tab'
)

outputs <- c(
  'plot_profile_allregiontypes_genes.pdf',
  'plot_profile_allregiontypes_tes.pdf'
)

labels <- c(
  "Number of Genes",
  "Number of TEs"
)

for (l in seq(from=1,to=length(hosts))){
  host = hosts[l]
  path = paths[l]
  
  count = length(treatment_file_endings)
  
  for (i in seq(from = 1, to = count)){
  
    treatment_file_ending = treatment_file_endings[i]
    
    output = outputs[i]
    
    label = labels[i]
    
    df <- data.frame(matrix(ncol = 3, nrow = 0))
    colnames(df) <- c("bin","val","label")
    
    # read in bin values for each track
    for (k in seq(from = 1, to = length(regions_bed))){
      
      region_bed = regions_bed[k]
      region = regions[k]
      
      file = paste(path, 'plot_profile_', region_bed, treatment_file_ending,sep='')
      
      df_read <- t(data.frame(fread(file)))
      
      ## need to do a lot of rearranging to get it into a format that works for ggplot
      df_temp <- data.frame( bin=as.vector(df_read[3:nrow(df_read),1]),
                        val=c(df_read[3:nrow(df_read),2]),
                        label=c(rep(region,nrow(df_read)-2)))
      
      df_temp$bin <- as.numeric(as.character(df_temp$bin))
      df_temp$val <- as.numeric(as.character(df_temp$val))
    
      df <- rbind(df, df_temp)
      }
    
    # make profile plot
    p <- ggplot(df, aes(x=bin, y=val, group=label)) + geom_line(aes(color=label), lwd=0.5) + theme_classic() +
          scale_x_continuous(labels=c('-5kbp', 'Start', 'End', '+5kbp'), breaks=c(1,500,750,1250)) + xlab('')+
          theme(axis.text=element_text(size=6), axis.title=element_text(size=6), legend.title=element_blank(), legend.text=element_text(size=8)) +                ylab(label)+
          theme(legend.position="none")+
      scale_color_manual(values=c(cbbPalette[1], cbbPalette[2], cbbPalette[3],
                                 cbbPalette[4], cbbPalette[5], cbbPalette[6]))
        
    ggsave(paste(host, '_', output,sep=''), plot=p, width=6.5/2, height=3/2)
    
  }
  
}



```

```{r}

## get legend for all plots
p <- ggplot(df, aes(x=bin, y=val, group=label)) + geom_line(aes(color=label), lwd=0.5) + theme_classic() +
      scale_x_continuous(labels=c('-0.5kb', 'Breakpoint', '0.5kb'), breaks=c(1,51,101)) + xlab('')+
      theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_blank(), legend.text=element_text(size=6)) +          ylab(label)+guides(color=guide_legend(ncol=6))+
      scale_color_manual(values=c(cbbPalette[1], cbbPalette[2], cbbPalette[3],
                                 cbbPalette[4], cbbPalette[5], cbbPalette[6]))

leg <- get_legend(p)
my_legend <- as_ggplot(leg)
ggsave('legend_abstract.pdf', plot = leg, width = 6.5, height = 0.25)

```

