---
title: "pfam_enrichment_plot"
output: html_document
date: '2022-10-14'
---

```{r}

library(ggplot2)
library(data.table)

```



```{r}

df <- data.frame(fread('pfam_enrichment.txt'))

df <- subset(df, select=-c(V1))


```

```{r}
## skip annotated just report as a written result instead

df <- df[df$domain != "unannotated",]

```

```{r}

## fix some names

df$domain[df$domain == "tyrosinase"] <- "Tyrosinase (melanin production)"

df$domain[df$domain == "kr"] <- "KR (polyketide synthesis)"

df$domain[df$domain == "het"] <- "HET (heterokaryon incompatbility)"

df$domain[df$domain == "aph"] <- "APH (antibiotic production)"

df$domain[df$domain == "acyl_transf"] <- "Acyltransferase"

df$domain[df$domain == "ketoacyl-synt"] <- "Beta-ketoacyl Synthase (fatty acid synthesis)"

df$domain[df$domain == "ps-dh"] <- "Dehydratase (polyketide synthesis)"

df$domain[df$domain == "polyprenyl_synt"] <- "Polyprenyl synthetase (isoprenoid synthesis)"

```

```{r}
df$p_value_fisher <- -log10(df$p_value_fisher)
```


```{r}



p <- ggplot(df, aes(x = ratio, y = factor(domain))) +
  geom_point(aes(color=p_value_fisher, size=annotated)) + theme_classic() +
  scale_colour_gradient(low = "blue", high = "red") +
  # geom_rect(mapping=aes(xmin=-Inf, xmax=1, ymin=-Inf, ymax=Inf), color="grey", alpha=0.01) + # rectangle shows the mark for observed/expected is 1
  xlab("Observed count over expected count") + ylab('')+ labs(color = "-Log10 p-value", size = "Number of orthogroups \nwith annotation")+theme(axis.text=element_text(size=6), axis.title=element_text(size=8), legend.title=element_text(size=8))+
  guides(colour = guide_colorbar(order = 1),
              size = guide_legend(order = 2))

ggsave(paste('pfam_pav_ogs_enrichment.pdf', sep = ''), plot = p, width = 6.5, height = 3)


```

