---
#MIT License
#
#Copyright (c) 2023 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "deletion_lengths"
output: html_document
date: '2022-11-10'
---

```{r}
library(data.table)
library(ggplot2)
```

```{r}

## read in deletion bed files for wheat blast and rice blast
df_rice <- data.frame(fread('../../pav_newest_gladieux_only_fungap/sv_callers/all_DEL.bed'))

colnames(df_rice) <- c('scaffold', 'start', 'end')

df_rice$length <- df_rice$end - df_rice$start

df_rice$host <- "MoO"

df_wheat <- data.frame(fread('../../pav_newest_wheat_blast_all/sv_callers/all_DEL.bed'))

colnames(df_wheat) <- c('scaffold', 'start', 'end')

# get deletion lengths
df_wheat$length <- df_wheat$end - df_wheat$start

df_wheat$host <- "MoT" 

# combine dfs

plot_df <- rbind(df_rice, df_wheat)

plot_df$length <- plot_df$length/1000

```

```{r}

median(df_rice$length)

```

```{r}

median(df_wheat$length)


```


```{r}

p <- ggplot(data=plot_df, aes(x=length, y=host, fill=host))+
  geom_violin(lwd=0.25, scale="width", adjust=5) + 
  geom_boxplot(width = 0.15, outlier.shape = NA,lwd=0.25, coef=0)+
    stat_summary(fun = "mean",
             geom = "point",
             color = "black",
             size=0.5)+
  xlab('Indel Lengths (kbp)')+
  ylab('')+
  xlim(0,15) +
  theme_classic()+
  theme(plot.title = element_text(size=8,hjust = 0.5), 
        axis.text=element_text(size=6),axis.title=element_text(size=8) , 
        legend.title=element_text(size=8), legend.position = 'bottom', 
        legend.text=element_text(size=6)) + theme(legend.title = 
                                                    element_blank())+
  theme(legend.position = "none")+
  scale_fill_manual(values=c("red", "blue"))

ggsave('deletion_lengths_density_plot.pdf', plot = p, width = 6.5/2, height = 4.5/2)

```

```{r}

permutation_test = function(vector1, vector2, stat, replicates){
    observed = stat(vector1) - stat(vector2)
    combined = c(vector1, vector2)

    null_dsn <- replicate(replicates,
                          {
                            sample_one_index <- sample(length(combined), length(vector1), replace = FALSE)
                            sample_two_index <- seq(length(combined))[!seq(length(combined))%in%sample_one_index]

                            sample_one <- combined[sample_one_index]
                            sample_two <- combined[sample_two_index]
                            stat(sample_one) - stat(sample_two)
                          })

    ## this is the two tailed p-value
    p_value <- mean(abs(observed)<=abs(null_dsn))

    if (p_value == 0){
      return(paste("<", as.character(1/replicates), sep=''))
    } else {
      return(as.character(p_value))
    }
}

twofive_quant = function(vector){
  return(unname(quantile(vector, 0.25)))
}

sevenfive_quant = function(vector){
  return(unname(quantile(vector,0.75)))
}

remove_outliers <- function(vector) {
  Q1 <- quantile(vector, 0.25)
  Q3 <- quantile(vector, 0.75)
  IQR <- Q3 - Q1
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q3 + 1.5 * IQR
  
  vector <- vector[vector >= lower_bound & vector <= upper_bound]
  return(vector)
}

```


```{r}

replicates <- 1000

col_names <- c(
  'rice_median',
  'wheat_median',
  'pvalue',
  'rice_mean',
  'wheat_mean',
  'rice_twofive_quant',
  'wheat_twofive_quant',
  'rice_sevenfive_quant',
  'wheat_sevenfive_quant'
)

df_stats <- data.frame(matrix(ncol = length(col_names), nrow = 0))

colnames(df_stats) <- col_names

df_subset = plot_df

test_1 = df_subset$length[df_subset$host == "MoO"]
test_2 = df_subset$length[df_subset$host == "MoT"]

## need to deal with missing values here
test_1 = na.omit(test_1)
test_2 = na.omit(test_2)

pvalue <- permutation_test(test_1, test_2, median, replicates)

output <- c(
        median(test_1), 
        median(test_2), 
        pvalue,
        ## remove outliers to match violin plot
        mean(remove_outliers(test_1)),
        mean(remove_outliers(test_2)),
        twofive_quant(test_1),
        twofive_quant(test_2),
        sevenfive_quant(test_1),
        sevenfive_quant(test_2))

df_stats[nrow(df_stats)+1,] <- output

write.csv(df_stats, '../distances_param_stats/deletion_lengths_stats.csv', row.names=FALSE)



```

