---
#MIT License
#
#Copyright (c) 2023 Pierre Michel Joubert
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
title: "pav_counts_cross_host"
output: html_document
date: '2022-11-11'
---

```{r}
library(data.table)
library(ggplot2)
```

```{r}

hosts <- c(
  'MoO',
  'MoT'
)

working_dirs <- c(
  'pav_newest_gladieux_only_fungap',
  'pav_newest_wheat_blast_all'
)

# names of lineages of interest
lineages_list <- list(
  c(2,3),
  c(1,2)
)

```



```{r}

count <- c()
percentage <- c()
label <- c()
category <- c()
lineage_column <- c()
host_column <- c()

for (i in seq(from=1,to=2)){
  working_dir = working_dirs[i]
  lineages <- unlist(lineages_list[i])
  host <- hosts[i]
  
  if (host == "MoO"){
    num_lineages = 2
  } else {
    num_lineages = 1
  }
  
  print(num_lineages)
  
  for (k in seq(from=1,to=num_lineages)){
    
    lineage <- lineages[k]
    
    ## get conserved and pav orthogroups
    conserved_file <- paste('../../', working_dir, '/pipeline_methods/conserved_ogs_', lineage, '.txt', sep = '')
    
    conserved_ogs <- read.table(conserved_file, header=FALSE, sep='\t')
    
    conserved_ogs <- conserved_ogs$V1
    
    # count
    conserved_ogs_count <- length(conserved_ogs)
    
    # same for pav ogs
    pav_file <- paste('../../', working_dir, '/pipeline_methods/actual_pav_ogs_', lineage, '.txt', sep = '')
    
    pav_ogs <- read.table(pav_file, header=FALSE, sep='\t')
    
    pav_ogs <- pav_ogs$V1
    
    pav_ogs_count <- length(pav_ogs)
    
    # and all ogs to get the "other" category
    all_file <- paste('../../', working_dir, '/pipeline_methods/all_ogs_', lineage, '.txt', sep = '')
    
    all_ogs <- read.table(all_file, header=FALSE, sep='\t')
    
    all_ogs <- all_ogs$V1
    
    all_ogs_count <- length(all_ogs)
    
    other_ogs_count <- all_ogs_count - conserved_ogs_count - pav_ogs_count
    
    count <- c(count, conserved_ogs_count, pav_ogs_count, other_ogs_count)
    
    percentage <- c(percentage,
                     conserved_ogs_count/all_ogs_count,
                     pav_ogs_count/all_ogs_count,
                     other_ogs_count/all_ogs_count)
    
    label <- c(label,
               'Conserved OGs',
               'PAV OGs',
               'Other OGs')
    
    lineage_column <- c(lineage_column,
                        rep(lineage,3))
    
    host_column <- c(host_column,
              rep(host,3))
  }
}

# putting it all together
df <- data.frame(count,percentage,label, lineage_column,host_column)

df$lineage_column <- as.character(df$lineage_column)

df$lineage_column[df$lineage_column == 1] <- "N/A"

```

```{r}

## complicated math to properly position the labels

label_df <- data.frame(df$percentage, df$count,df$label,df$lineage_column, df$host_column)

colnames(label_df) <- c('percentage','count','label','lineage_column','host_column')

label_df$position <- 0

label_df$position[label_df$label == 'Conserved OGs'] <- label_df$percentage[label_df$label == 'PAV OGs'] +
                                                    label_df$percentage[label_df$label == 'Other OGs'] +
                                                    label_df$percentage[label_df$label == 'Conserved OGs']/2

label_df$position[label_df$label == 'PAV OGs'] <- label_df$percentage[label_df$label == 'PAV OGs']/2

label_df$position[label_df$label == 'Other OGs'] <- 1 - label_df$percentage[label_df$label == 'Conserved OGs'] +
                                                  label_df$percentage[label_df$label == 'Other OGs']/2

label_df <- label_df[label_df$label != "Other OGs",]

```


```{r}

## plot stacked barplot with text representing the counts per category
p <- ggplot(df, aes(x = lineage_column, fill = label, y = percentage)) +
  geom_bar(stat = 'identity', position = 'fill')+
    geom_text(data=label_df, aes(y=position,x=lineage_column,label=scales::comma(count)), size=6*0.36)+
  theme_classic()+
  facet_grid(. ~ host_column,scales="free_x")+
  ylab('Proportion')+
  xlab('Lineage')+
    theme(plot.title = element_text(size=8,hjust = 0.5), axis.text=element_text(size=6),axis.title=element_text(size=6) , legend.title=element_text(size=8), legend.position = 'left', legend.text=element_text(size=6)) + theme(legend.title = element_blank())+
theme(strip.text.x = element_text(size = 6))+
  theme(legend.margin=margin(t = 0, unit='mm'))+
  theme( strip.background = element_blank() )+
  scale_fill_manual(values = c("red", "gray", "blue"))

ggsave('pav_counts_stacked_barplot.pdf', plot = p, width = 6.5/2, height = 4.5/2)

```

